---  
- hosts: localhost  
  gather_facts: no  
  connection: local   
  vars:  
    #your region  
    region: ap-southeast-1   
  tasks:  
    - name: EC2 provisioning with general purpose EBS volume 
      ec2:
        region: "ap-southeast-1"  
        key_name: stratpoint 
        instance_type: t2.micro  
        image: ami-dc361ebf      
        group: AWS-Admin-Group
        volumes:
          - device_name: /dev/sda1
            device_type: gp2
            volume_size: 100
            delete_on_termination: true
